-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 08:52:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema primeiro_modelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema primeiro_modelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `primeiro_modelo` DEFAULT CHARACTER SET utf8 ;
USE `primeiro_modelo` ;

-- -----------------------------------------------------
-- Table `primeiro_modelo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_modelo`.`estado` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_modelo`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_modelo`.`cidade` (
  `idtable2` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `estado_idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable2`),
  INDEX `fk_cidade_estado1_idx` (`estado_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idtable1`)
    REFERENCES `primeiro_modelo`.`estado` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_modelo`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_modelo`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `nasc` DATE NOT NULL,
  `CPF` INT NULL,
  `end_rua` VARCHAR(12) NOT NULL,
  `end_nro` INT NULL,
  `end_compl` VARCHAR(120) NULL,
  `CEP` INT NULL,
  `cidade_idtable2` INT NOT NULL,
  `estado_idtable1` INT NOT NULL,
  PRIMARY KEY (`idclientes`),
  INDEX `fk_clientes_cidade_idx` (`cidade_idtable2` ASC) VISIBLE,
  INDEX `fk_clientes_estado1_idx` (`estado_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_cidade`
    FOREIGN KEY (`cidade_idtable2`)
    REFERENCES `primeiro_modelo`.`cidade` (`idtable2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_estado1`
    FOREIGN KEY (`estado_idtable1`)
    REFERENCES `primeiro_modelo`.`estado` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
