# -*- coding: utf-8 -*-
"""bioinfo_m2_tuplas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTXfpcd13Y29LIlUx2DiPKQZOG94JkYJ

#Introdução à Computação para Bioinformática 2022/1
#Exercícios práticos - Variáveis - Listas
#Luan Carlos
"""

amino = ('A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y')

# A) Conte e imprima o número de elementos contidos na tupla criada.

print(len(amino))



# B) Veriﬁque e imprima se o aminoácido Serina (S) pertence à tupla. 

'S' in amino

# C) Crie uma segunda tupla contendo os elementos Prolina (P), Glicina (G), Asparagina (N), Tirosina (Y), Valina (V) e Triptofano (W).  

amino2 = ('P', 'G', 'N', 'Y', 'V', 'W')


# D) Some as tuplas construídas e imprima o resultado. 

amino3 = amino + amino2
print(amino3)

# E) Conte a ocorrência dos elementos Glicina (G), Asparagina (N) e Cisteína (C).

print(amino3.count('G'))
print(amino3.count('N'))
print(amino3.count('C'))

# F) Retorne a posição do primeiro elemento Asparagina (N). 

print(amino3.index('N'))

# G) Retorne os 5 últimos elementos da tupla. 

print(amino3[-5:])