# -*- coding: utf-8 -*-
"""bioinfo_m2_dicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2Abw83WC0UsBzkrEAqnm9BEKFzNmbpx

#Introdução à Computação para Bioinformática 2022/1
#Exercícios práticos - Variáveis - Dicionários
#Luan Carlos
"""

# A) Construa um dicionário onde os ids PDB sejam as chaves e o número de resíduos de aminoácidos sejam o valor.  
# B) Imprima os valores contidos nos ids 2TNF e 2E7A.

prot = {'1A8M': 471, '1TNR': 283, '2AZ5': 592, '1TNF': 471, '2TNF': 468, '2TUN': 942, '4TSV': 150, '5TSW': 900, '2E7A': 471, '6RMJ': 489}
print(prot['2TNF'], prot['2E7A'])

# C) Veriﬁque e imprima o tamanho do dicionário construído  

len(prot)

# D) Obtenha e imprima a lista de todas as chaves do dicionário 

prot.keys()

# E) Obtenha e imprima a lista de todos os valores do dicionário

prot.values()

# F) Obtenha e imprima uma lista de tuplas com todos os pares chave-valor. Cada dupla será um par ordenado (chave, valor).

prot.items()