# -*- coding: utf-8 -*-
"""bioinfo_m2_strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMPRllGsVxg2MMw2uYxzTGqtd7FkZwqR

#Introdução à Computação para Bioinformática 2022/1
#Exercícios práticos - Variáveis - Dicionários
#Luan Carlos
"""

# ------------- 1ª QUESTÃO -------------

seq = 'VRSSSRTPSDKPVAHVVANPQAEGQLQWLNRRANALLANGVELRDNQLVVPSEGLYLIYSQVLFKGQGCPSTHVLLTHTISRIAVSYQTKVNLLSAIKSPCQRETPEGAEAKPWYEPIYLGGVFQLEKGDRLSAEINRPDYLLFAESGQVYFGIIAL'

#a
len(seq)

#b
seq.count('LL')

#c
print(seq.find('GG'))
print(seq.find('RR', seq.find('GG')))

#c
seq.find('GG')
seq.find('RR', seq.find('GG'))

#d
seq[:100]

#e
seq.replace('SSSR', 'AAAA')

#f
seq2 = seq.replace('SSSR', 'AAAA')
seq2.split('AAAA')

# ------------- 2ª QUESTÃO -------------
txt = "As proteínas são cadeias polipeptídicas formadas pela ligação peptídica entre resíduos de aminoácidos. Existem 20 tipos de aminoácidos comumente encontrados nos seres vivos. A esses aminoácidos, foram atribuídas abreviações de 3 letras e símbolos de 1 letra. As abreviações de 3 letras são bastante evidentes consistindo nas três primeiras letras do se nome." 

#a
txt.upper()

#b
txt.lower()

#c
txt.title()

#d
txt.swapcase()

# ------------- 3ª QUESTÃO -------------
insulin_signal = 'MALWMRLLPLLALLALWGPDPAAA'

#a
len(insulin_signal)

#b
quebra = 'LLALLALWG'
insulin_signal.split(quebra)

#c
insul_nova = insulin_signal.split(quebra)
insul_nova = ''.join(insul_nova)
insul_nova

#d
insulin_signal.replace('DPAAA', 'LLALL')

# ------------- 4ª QUESTÃO -------------
dna = 'GATGGAACTTGACGTAAACCTATATT'
dna.replace('T', 'U')