# -*- coding: utf-8 -*-
"""bioinfo_m2_conjuntos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YWnlrbbXJUzsET9bfM0JgYKmSH3x-wg

#Introdução à Computação para Bioinformática 2022/1
#Exercícios práticos - Variáveis - Conjuntos
#Luan Carlos
"""

# ================ 1ª QUESTÃO ================

# A) Veriﬁque as diferenças entre os conjuntos (1,2) (1,3) e (2,3)

ferr1 = {1.9, 1.8, 5.7, 1.6, 5.8, 1.7, 9.6, 5.9, 9.5, 6.5, 6.2, 1.1, 4.4, 3.5, 2.9, 4.7, 4.6, 5.2, 5.3}
ferr2 = {4.7, 3.6, 6.2, 7.1, 7, 5.6, 5.7, 3.4, 3.3, 2.1, 3.8, 3.9, 5, 5.1, 1.9, 9.5, 1.0, 1.3, 5.4}
ferr3 = {2.2, 3.3, 5.1, 3, 3.7, 9.1, 8.8, 8.5, 2, 4.1, 6.1, 4.9, 1.1, 0.5, 0.8, 3.2, 6.9, 9.3, 9.5}

print(ferr1.difference(ferr2))
print(ferr1.difference(ferr3))
print(ferr2.difference(ferr3))

# B) Retorne as intersecções entre (1,2) (1,3) e (2,3)

print(ferr1.intersection(ferr2))
print(ferr1.intersection(ferr3))
print(ferr2.intersection(ferr3))

# C) Insira todos os elementos do conjunto 2 e 3 no conjunto 1
# D) Retorne o tamanho do conjunto formado pela tarefa (c).

ferr1.update(ferr2, ferr3)

print(ferr1)
len(ferr1)

# ================ 2ª QUESTÃO ================

A = {3, 6, 9, 12, 15, 18, 21, 24, 28, 27}
B = {2, 6, 8, 10, 14, 16, 18, 20, 22, 24}
C = {2, 6, 10, 18, 20}
D = {1, 30, 5, 11, 17, 16, 22, 26}

# A) Veriﬁque a interseção e diferença entre o conjunto A e B.

print(A.intersection(B))
print(A.difference(B))

# B) Veriﬁque se o conjunto A e B são disjuntos ao conjunto D

print(A.isdisjoint(D))
print(B.isdisjoint(D))

# C) Retorne se o conjunto C é subconjunto de A e B

print(C.issubset(A))
print(C.issubset(B))

# D) Acrescente os elementos 18, 23, 25, 63 no conjunto D

print(len(D))
D.update([18, 23, 25, 63])
print(D)
print(len(D))